indexer:
  environment: indexer
  description: Deploy Blockcore Indexer
  payload:
    chain: "BTC"
    version: "v0.0.2"

explorer:
  environment: explorer
  description: Deploy Blockcore Explorer
  payload:
    chain: "BTC"
    version: "v0.0.2"
